name: Deploy to Vercel Pages
author: CustomAFK
description: Publish a static site to Vercel page on PR Update

inputs:
  VERCEL_TOKEN:
    description: Vercel Access Tokens are required to authenticate and use the Vercel API
    required: true
  VERCEL_PROJECT_ID:
    description: Vercel Project Id
    required: true
  VERCEL_ORG_ID:
    description: Vercel ORG ID
    required: true

runs:
  using: composite
  steps:
    - name: Install Vercel CLI
      shell: bash
      run: yarn global add vercel

    - name: Pull Vercel Environment Information
      shell: bash
      run: vercel pull --yes --environment=preview --token=${{ inputs.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      shell: bash
      run: vercel build --token=${{ inputs.VERCEL_TOKEN }}

    - name: Deploy Project Artifacts to Vercel
      shell: bash
      run: vercel deploy --prebuilt --token=${{ inputs.VERCEL_TOKEN }}
