name: Deploy on Enviroment Dev
on:
  pull_request:
    branches:
      - 'master'
      - 'development'
    types:
      - closed
jobs:
  test_preview:
    runs-on: self-hosted
    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Install package use Yarn
        run: |
          echo "We using yarn to install package!"
          npm install

      - name: Check format
        run: |
          echo "Using pettier check"
          npm run format

      - name: Build Yarn
        run: |
          echo "Yarn is Building"
          npm run build
