name: Deploy on Enviroment Dev
on:
  pull_request:
    branches:
      - 'master'
      - 'development'
    types:
      - closed
jobs:
  test_preview:
    runs-on: self-hosted
    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Install package use Yarn
        run: |
          echo "We using yarn to install package!"
          yarn install

      - name: Check format
        run: |
          echo "Using pettier check"
          yarn format

      - name: Build bunx
        run: |
          echo "Yarn is Building"
          yarn build
          # sudo rm -rf /var/www/ie106
          # sudo cp -r /home/ubuntu/ie106-front-end/_work/ie106-front-end/ie106-front-end/dist/ /var/www/ie106/
